"""empty message

Revision ID: 3e1c7a9de64f
Revises: 8b21b760ed9b
Create Date: 2019-04-15 09:44:53.066476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1c7a9de64f'
down_revision = '8b21b760ed9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertimes',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handler', sa.String(), nullable=True),
    sa.Column('timeSpent', sa.String(), nullable=True),
    sa.Column('lastActiveDay', sa.String(), nullable=True),
    sa.Column('totalTime', sa.String(), nullable=True),
    sa.Column('noOfDays', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertimes')
    # ### end Alembic commands ###
