"""empty message

Revision ID: 8b21b760ed9b
Revises: 
Create Date: 2019-03-03 14:49:21.728456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b21b760ed9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edits',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handler', sa.String(), nullable=True),
    sa.Column('finalTweet', sa.String(), nullable=True),
    sa.Column('edits', sa.String(), nullable=True),
    sa.Column('noOfEdits', sa.String(), nullable=True),
    sa.Column('messageShown', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('handler', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handler')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('edits')
    # ### end Alembic commands ###
